# Generated by Django 3.2.5 on 2021-12-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_items_item'),
        ('shop', '0002_auto_20211210_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
