# Generated by Django 3.2.5 on 2021-12-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211210_2007'),
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
    ]
